### ISSUE TITLE
Connection to DAM fails

### ISSUE THREAD

**Issue by ghost** [Institute-Web-Science-and-Technologies/koldfish-dam#3]
When I execute the following code
`try {
      // Random random = new Random();
      dam = new JmsDataAccessModule();// new DummyDataAccessModule(random);
      DataAccessModuleListener listener = new StorageListenerImpl(tripleStoreURL);
      dam.addListener(listener);
      dam.start();
    } catch (Exception e) {
      log.error(e);
      throw new RuntimeException(e);
    }`

the following exception is thrown:

`Exception in thread "main" java.lang.RuntimeException: javax.jms.InvalidClientIDException: Broker: localhost - Client: Koldfish-Dictionary already connected from tcp://141.26.208.184:51763
    at de.unikoblenz.west.koldfish.dataService.backend.DataServiceBackend.<init>(DataServiceBackend.java:103)
    at de.unikoblenz.west.koldfish.dataService.backend.impl.DataServiceBackendImpl.<init>(DataServiceBackendImpl.java:46)
    at de.unikoblenz.west.koldfish.dataService.backend.impl.DataServiceBackendImpl.main(DataServiceBackendImpl.java:125)
Caused by: javax.jms.InvalidClientIDException: Broker: localhost - Client: Koldfish-Dictionary already connected from tcp://141.26.208.184:51763
    at org.apache.activemq.broker.region.RegionBroker.addConnection(RegionBroker.java:255)
    at org.apache.activemq.broker.jmx.ManagedRegionBroker.addConnection(ManagedRegionBroker.java:230)
    at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:98)
    at org.apache.activemq.advisory.AdvisoryBroker.addConnection(AdvisoryBroker.java:116)
    at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:98)
    at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:98)
    at org.apache.activemq.broker.MutableBrokerFilter.addConnection(MutableBrokerFilter.java:103)
    at org.apache.activemq.broker.TransportConnection.processAddConnection(TransportConnection.java:817)
    at org.apache.activemq.broker.jmx.ManagedTransportConnection.processAddConnection(ManagedTransportConnection.java:77)
    at org.apache.activemq.command.ConnectionInfo.visit(ConnectionInfo.java:139)
    at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:338)
    at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:188)
    at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:50)
    at org.apache.activemq.transport.WireFormatNegotiator.onCommand(WireFormatNegotiator.java:125)
    at org.apache.activemq.transport.AbstractInactivityMonitor.onCommand(AbstractInactivityMonitor.java:300)
    at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)
    at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:233)
    at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:215)
    at java.lang.Thread.run(Thread.java:745)
`

**Comment by lkastler** [comment]
@martinleinberger problem occurred most in Koldfish-dictionary by adding the connections.properties.
